version: '3'
services:
  liberty-agent:
    image: liberty-container.kr.ncr.ntruss.com/liberty-agent:latest
    ports:
      - "8501:8501"
    env_file:
      - .env.prod
    environment:
      - OPENAI_API_KEY
      - PINECONE_API_KEY
      - PINECONE_INDEX_NAME
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'