name: Deploy to NCR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    environment: liberty-NCP-streamlit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Login to NCR
        run: |
          echo "${{ secrets.NCR_SECRET_KEY }}" | docker login liberty-container.kr.ncr.ntruss.com \
            --username "${{ secrets.NCR_ACCESS_KEY }}" --password-stdin

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: liberty.Dockerfile
          push: true
          tags: liberty-container.kr.ncr.ntruss.com/liberty-agent:latest