name: Deploy to NCR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.10'
          
      - name: Run Streamlit Test
        run: |
          pip install -r requirements.txt
          python test_streamlit.py

      - name: Set Environment Variables
        run: |
          echo "NCR_ACCESS_KEY=${{ secrets.NCR_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "NCR_SECRET_KEY=${{ secrets.NCR_SECRET_KEY }}" >> $GITHUB_ENV

      - name: Check Secrets
        run: |
          echo "ACCESS_KEY=${NCR_ACCESS_KEY}"
          echo "SECRET_KEY=${NCR_SECRET_KEY}"

      - name: Test NCR Login
        run: |
          docker login liberty-container.kr.ncr.ntruss.com \
            -u $NCR_ACCESS_KEY \
            -p $NCR_SECRET_KEY
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Check Secrets
        run: |
          echo "NCR_ACCESS_KEY=${NCR_ACCESS_KEY:0:4}***"
          echo "NCR_SECRET_KEY=${NCR_SECRET_KEY:0:4}***"
          echo "UPSTAGE_API_KEY=${{ secrets.UPSTAGE_API_KEY:0:4 }}***"

      - name: Set Environment Variables
        run: |
          echo "NCR_ACCESS_KEY=${{ secrets.NCR_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "NCR_SECRET_KEY=${{ secrets.NCR_SECRET_KEY }}" >> $GITHUB_ENV
      - name: Test NCR Login
        run: |
          echo "$NCR_ACCESS_KEY" | docker login liberty-container.kr.ncr.ntruss.com -u $NCR_ACCESS_KEY --password-stdin    
      - name: Login to NCR
        uses: docker/login-action@v2
        with:
          registry: liberty-container.kr.ncr.ntruss.com
          username: ${{ secrets.NCR_ACCESS_KEY }}
          password: ${{ secrets.NCR_SECRET_KEY }}

      - name: Set environment variable
        run: |
          echo "UPSTAGE_API_KEY=${{ secrets.UPSTAGE_API_KEY }}" >> .env.prod
          echo "PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}" >> .env.prod
          echo "PINECONE_INDEX_NAME=${{ secrets.PINECONE_INDEX_NAME }}" >> .env.prod
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env.prod
          echo "LANGCHAIN_API_KEY=${{ secrets.LANGCHAIN_API_KEY }}" >> .env.prod
          echo "LANGCHAIN_ENDPOINT=${{ secrets.LANGCHAIN_ENDPOINT }}" >> .env.prod
          echo "LANGCHAIN_PROJECT=${{ secrets.LANGCHAIN_PROJECT }}" >> .env.prod
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: liberty-container.kr.ncr.ntruss.com/liberty-agent:latest 