name: Deploy to NCR

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to NCR
        uses: docker/login-action@v1
        with:
          registry: liberty-container.kr.ncr.ntruss.com
          username: ${{ secrets.NCR_ACCESS_KEY }}
          password: ${{ secrets.NCR_SECRET_KEY }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: liberty-container.kr.ncr.ntruss.com/liberty-agent:latest 